[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/.netlify/functions/*"
    [headers.values]
      Access-Control-Allow-Headers = "Content-Type, Authorization"
      Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
      Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-proxy?path=:splat"
  status = 200

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_API_BASE_URL"