[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Configure secrets scanning to ignore common patterns
  SECRETS_SCAN_OMIT_PATHS = "dist/,node_modules/,*.log,debug-*"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin", "editor"], Country = ["US"]}

# Basic redirects for clean URLs
[[redirects]]
  from = "/listings"
  to = "/listings.html"
  status = 200

[[redirects]]
  from = "/profile"
  to = "/profile.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/register.html"
  status = 200
